<?php echo $this->doctype();?>

<html>
<head>
<?php echo $this->headTitle();?>
<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />
<?php 
$this->headMeta()->appendName('robots', 'NOINDEX,NOFOLLOW,NOARCHIVE,NOODP,NOSNIPPET');
echo $this->headMeta(); ?>

<?php echo $this->headLink(); ?>

<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>

</head>
<body class="login">
<header>
<?php if(isset($this->user)) {?>

<?=$this->render('partials/topBar.phtml')?>

<?php }else{?>
<div id="rastro">
	<a onclick="" href="javascript:history.back(1);" title=""> <?php echo $this->translate->_('Volver')?></a>
</div>
<?php }?>
</header>

<?php echo $this->layout()->content;?>


<!-- SSID <?=Zend_Session::getId()?> --> 

</body>
</html>