<?php echo $this->doctype()?>
<html>
	<head>
		<?php echo $this->headTitle();?>
		<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />
		<?php 
		$this->headMeta()->appendName('robots', 'NOINDEX,NOFOLLOW,NOARCHIVE,NOODP,NOSNIPPET');
		echo $this->headMeta(); ?>
		
		<?php echo $this->headLink(); ?>
		
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	
	<body style="background-color:#EEE">
		<?php echo $this->layout ()->content; ?>
	</body>
</html>