<div id="asignarTask" title="<?=$this->translate('Asignar tarea')?>" style="display:none">
	<p class="validateTips"><?=$this->translate('Click en el nombre de la persona para asignar / desasignar la tarea.')?></p>
	
	<div class="loading">
		<div id="loadinger">
			<img src="/img/preloader.gif" /> <div><?=$this->translate('Cargando información...')?></div>
		</div>
	</div>
	
	<ul id="memberList" class="listSelect"></ul>
</div>