<div id="createNewTemplate"  title="<?=$this->translate('Crear nueva Plantilla')?>" style="display:none;z-index:95002 !important">
	<div class="administrarApp">
		<!--<div class="title"><?=$this->translate('Create new Template')?></div>-->	
		<div class="description">
			<?=$this->translate('Puede crear templates en esta pestaña.<br />
			Los templates son utilizados para crear la lista de eventos chekclist.')?>

		</div>		
		<div class="content">
			<form id="new1_template_form" enctype='application/json' action="" method="" class="">
				<dl class="zend_form">
				 <h3 class="temp-new"><?=$this->translate('General Information')?><img src="/img/details_close.png" alt="" class="img_sty" style="float:right;opacity: 0.4;filter: alpha(opacity=40);"/></h3>
				 <div id="section_1">
					<fieldset>
						<label for="new1_title"><?=$this->translate('Template Title')?></label>
						<input type="text" name="__@@__title" id="new1_title" class="needed_tem" placeholder="<?=$this->translate('Set Title...')?>" />
						<label for="new1_description"><?=$this->translate('Template Description')?></label>
						<textarea id="new1_description" style="height: 20px;" class="textareas needed_tem" name="__@@__description" placeholder="<?=$this->translate('Set the description for this template...')?>"></textarea>
						<!--<label for="new1_remark"><?=$this->translate('Remark')?></label>
						<textarea id="new1_remark" style="height: 15px;" class="textareas" name="remark" placeholder="<?=$this->translate('Remarks...')?>"></textarea>-->
					</fieldset>
				</div>
				<h3 class="temp-new"><?=$this->translate('Asignament Options')?><img src="/img/details_open.png" alt=""  class="img_sty" style="float:right;"/></h3>
				 <div id="section_2" class="oculto">
					<!--<fieldset class="col-b">
						<label for="form_grupo" class=""><?=$this->translate('A realizar por el grupo')?></label>
						<input type="text" name="max" id="form_grupo" value="" class="" placeholder="<?=$this->translate('Seleccione...')?>" /> 
						<select id="form_grupo" name="subgrupo">
							<option value="-1"><?=$this->translate('Cualquiera')?></option>
							<?php 
							for($i=0;$i<count($this->subgrupos);$i++)
							{
								echo '<option value="'.$this->subgrupos[$i]['id'].'">'.$this->subgrupos[$i]['name'].'</option>';
							}
							?>
						</select>
						<img src="/img/icon/information.png" alt="" title="<?=$this->translate('Utilice el planificador para gestionar los grupos.')?>"/>
					</fieldset>
					<fieldset class="col-b last">
						<label for="form_user" class=""><?=$this->translate('A realizar por el usuario')?></label>
						<input type="text" name="limite" id="form_user" value="" class="" placeholder="<?=$this->translate('Seleccione...')?>" />
						<select id="form_user" name="uid">
							<option value="-1"><?=$this->translate('Cualquiera')?></option>
							<?php 
							for($i=0;$i<count($this->colegas);$i++)
							{
								echo '<option value="'.$this->colegas[$i]['id'].'">'.$this->colegas[$i]['name'].'</option>';
							}
							?>
						</select>
						<img src="/img/icon/information.png" alt="" title="<?=$this->translate('Usuarios pertenecientes al grupo seleccionado, utilice el planificador si desea gestionarlos.')?>"/>
					</fieldset>	-->	

					<fieldset class="col-b">
						<label for="new1_shifts" class=""><?=$this->translate('Shifts:')?></label>
						<select name="__@@__turno" class="" id="new1_shifts">
							<option value="Morning"><?=$this->translate('Morning')?></option>
							<option value="Evening"><?=$this->translate('Evening')?></option>
							<option value="Night"><?=$this->translate('Night')?></option>
						</select>
					</fieldset>
					
					<fieldset class="col-b last">
						<!--  <label for="new1_location" class=""><?=$this->translate('Select:')?></label>-->
						<!-- <input type="text" name="limite" id="form_user" value="" class="" placeholder="<?=$this->translate('Seleccione...')?>" /> -->
						<select name="__@@__centro" class="" id="new1_location" style="display:none;">
							<!--<option value=""><?=$this->translate('Select Location')?></option>-->
							<option selected="selected" value="BCN - 22@"><?=$this->translate('BCN - 22@')?></option>
							<!--  <option value="MAD - 28@"><?=$this->translate('MAD - 28@')?></option>-->
						</select>
					</fieldset>		
					<fieldset class="col-a">
    					<label class="" for="new1_group"><?=$this->translate('Asigned Group')?></label>
    					<!--<input type="text" name="__@@__group" id="new1_group" class="needed_tem Upper" placeholder="<?=$this->translate('GENE, MULTI, INTER...')?>" />-->

    					 <select name="__@@__group" id="new1_group" placeholder="<?=$this->translate('Required Fields...')?>" value="" class="needed_tem Upper">
                        <?php 
                        $tmp = $this->Groups()->GetAllGroups();
                        foreach ($tmp as $cli)
                        {
                            echo $cli;
                        }
                        
                        
                        ?>
                        </select>
					</fieldset>
					
					<fieldset class="col-a">
    					<label class="" for="new1_client"><?=$this->translate('Select:')?></label>			
    				    <!--  <input type="text" name="__@@__client" id="new1_client" class="needed_tem Upper" placeholder="<?=$this->translate('All, MULTI, INTER...')?>" />-->
    				    <select name="__@@__client" class="" id="new1_client">
    				    	<!--<option value=""><?=$this->translate('Select Location')?></option>-->
    				    	<?php 
    				    	   $clisTmp = $this->Clientes()->GetAll();
    				    	   foreach($clisTmp as $cliTmp){
    				    	       echo $cliTmp;
    				    	   }
    				    	?>
    				    </select>
    				    
					</fieldset>

					<fieldset style="display: none;" class="col-a last">
    					<label class="" for="new1_rgroup"><?=$this->translate('Responsible Group')?></label>	
    					<input type="text" name="__@@__rgroup" id="new1_rgroup" class="" placeholder="<?=$this->translate('COP, WINTEL, TOOLS, BACKUP ...')?>" />				
					</fieldset>
				</div>				
				<h3 class="temp-new"><?=$this->translate('Date/Time Options')?><img src="/img/details_open.png" alt=""  class="img_sty" style="float:right;"/></h3>
				 <div id="section_3" class="oculto">
				<!--	<fieldset class="col-a">
						
						<label class="" for="new1_allday"><?=$this->translate('All Day')?></label>
						<div style="border: 1px solid #ccc;border-top-color: #EEEEEE;">
							<input type="checkbox" name="__@@__allday" class="" id="new1_allday" value="0" />
						</div>
					</fieldset>-->
					
					<fieldset class="col-b">
						<label for="new1_time_start" class=""><?=$this->translate('Start Time')?></label>
						<input type="text" class="" name="__@@__t_start" id="new1_time_start" value="10:00">
					</fieldset>
					
					<fieldset class="col-b last">
						<label for="new1_time_end" class=""><?=$this->translate('End Time')?></label>
						<input type="text" name="__@@__t_end" id="new1_time_end" value="11:00" class="">
					</fieldset>
				</div>				
				<h3 class="temp-new"><?=$this->translate('Recurring Options')?><img src="/img/details_open.png" alt=""  class="img_sty" style="float:right;"/></h3>
				<div id="section_3" class="oculto">
					<fieldset class="col-b">
						<label for="repeats" class=""><?=$this->translate('Repeat')?></label>
						<div style="border: 1px solid #ccc;border-top-color: #EEEEEE;height:50px;background-color: #fafafa;">
							<input type="checkbox" style="float:left;display:inline;margin:4% 0px 5px 25px;" name="repeats" id="new1_repeats" value="0" class="">
						<select name="repeat-options" id="new1_repeat-options" style="display:none;width:60%;float:right; margin:6px;">
								<option value="1"><?=$this->translate('Weekly')?></option>
								<!--<option value="0"><?=$this->translate('Day')?></option>
								<option value="2"><?=$this->translate('Monthly')?></option>
								<option value="3"><?=$this->translate('Yearly')?></option>-->
						</select>
						</div>
						
					</fieldset>
					<fieldset class="col-b last">
						<label for="end-repeat"><?=$this->translate('Repeat until:')?></label>
						<div id="repeat_until_container">								
							<input type="text" style="height:45px" name="end-repeat" id="new1_end-repeat" disabled />
						</div>
					</fieldset>
				<div class="repeat-fieldset-frame">
					<fieldset id="1_detail" class="repeat-fieldset" style='margin: 0 5px 5px 5px;float:right;'>
					    	<legend><?=$this->translate('Weekly')?></legend>
					    	<div>
							<label for="1_detail_type"style="border:0;background-color: #ffe8ef;box-shadow: 0 0 0 rgba(0, 0, 0, 0) inset;"><?=$this->translate('Repeat Every ')?></label>
					    		<p style="text-align:left">

					    		<span>
					    		<?php 
					    		$timestamp = strtotime('next Monday');
					    		$days = array();
					    		for ($i = 1; $i < 8; $i++) {
					    			$days = strftime('%A', $timestamp);
					    			$timestamp = strtotime('+1 day', $timestamp);
					    			
					    			echo "<label for='$days' style='border:0;background-color: #ffe8ef;box-shadow: 0 0 0 rgba(0, 0, 0, 0) inset;margin: 0 5px 5px 5px;width: 50px;float:right;'>".$this->translate($days)."</label>";
					    			echo "<input type='checkbox' style='margin: 10px 10px 10px 10px;width: 14px; height: 14px;float:right;' class='day_chk' name='day_checkbox' id='$i"."_new_1' value='$i'/>";
					    			if($i =='3') echo'<br />';
					    		}
					    		
					    		
					    		?></span></p>
					    	</div>
					    </fieldset>	
					
				</div>
				</div>

				
				<h3 class="temp-new"><?=$this->translate('Environment Options')?><img src="/img/details_open.png" alt=""  class="img_sty" style="float:right;"/></h3>
				<div id="section_4" class="oculto">
					<!--
					<dt id="incident-label">
					<label for="incident" class="optional">Incident/Change Number:</label>
					</dt>
					<dd id="incident-element">
						<input type="text" name="incident" id="new1_incident" value="">
					</dd>-->
					
					<fieldset class="col-a">
						<label for="new1_environment" class=""><?=$this->translate('Environment')?></label>
						<select name="__@@__environment" id="new1_environment">
							<option value=""><?=$this->translate('Select Environment')?></option>
							<option value="PRO"><?=$this->translate('PRO')?></option>
							<option value="PRE"><?=$this->translate('PRE')?></option>
							<option value="DES"><?=$this->translate('DES')?></option>
							<option value="INTEG"><?=$this->translate('INTEG')?></option>
						</select>
					</fieldset>
					
					<fieldset style="display: none;" class="col-a">
						<input type="text" name="__@@__origen" class="" id="new1_source" value="Checklist" />
						
					</fieldset>

					<fieldset style="display: none;" class="col-a">
						
						<input type="text" name="__@@__type" class="" id="new1_type" value="Manual"/>
						
					</fieldset>
					</div>
				
				
<h3 class="temp-new"><?=$this->translate('Service Manager')?><img src="/img/details_open.png" alt=""  class="img_sty" style="float:right;"/></h3>
<div id="section_5" class="oculto">
	<fieldset class="col-b">
		<label for="open-close-ticket" class=""><?=$this->translate('Open/Close Ticket')?></label>
		<div style="border: 1px solid #ccc;border-top-color: #EEEEEE;height:50px;background-color: #fafafa;">
			<input type="checkbox" style="width: 100px;float:left;display:inline;" name="__@@__open-close-ticket" id="new1_open-close-ticket" value="1" class="">
		</div>
	</fieldset>
	<fieldset class="col-b last">
		<label for="minutes-close-ticket"><?=$this->translate('Minutes for closing ticket:')?></label>
		<div id="minutes-close-ticket_container">			
			<input id="new1_minutes-close-ticket" class="minutesCloseTicket" style="height:45px" placeholder="<?=$this->translate('Max. 60 minutes')?>" name="__@@__minutes-close-ticket" type="text" disabled="disabled">
		</div>
	</fieldset>
</div>

			<!-- 		<dt id="operator-label">
						<label for="operator" class="optional">Operator:</label>
					</dt>
					<dd id="operator-element">
						<input type="text" name="operator" id="new1_operator" value="">
					</dd> -->
					
					<dt id="Guardar-label">&nbsp;</dt>
					<dd id="Guardar-element">
						<!-- <input type="button" style="width: 47%; display: none;" name="update" id="new1_update" value="Create Event">-->
						<div id="new1_savecontain">
						<input type="button" style="opacity:0.5;width: 47%; float:right; clear:both;" name="save" id="new1_save" value="Save Template" class="new_save"></div>
						<input type="hidden" name="__@@__template"  id="new1_temp" value="Y">
						<input type="hidden" name="__@@__re_value_recur" value="" id="new1_value_recur">
						<input type="hidden" name="tareaid" value="" id="new1_tareaid">
					</dd>
					</div>
 
					
				</dl>

			</form>

</div>
</div>



<script type="text/javascript">

$(function() {

	$(".minutesCloseTicket").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
             // Allow: Ctrl/cmd+A
            (e.keyCode == 65 && (e.ctrlKey === true || e.metaKey === true)) ||
             // Allow: Ctrl/cmd+C
            (e.keyCode == 67 && (e.ctrlKey === true || e.metaKey === true)) ||
             // Allow: Ctrl/cmd+X
            (e.keyCode == 88 && (e.ctrlKey === true || e.metaKey === true)) ||
             // Allow: home, end, left, right
            (e.keyCode >= 35 && e.keyCode <= 39)) {
                 // let it happen, don't do anything
                 return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
            
        } else {


        	// Validar valores minimo y maximo
        	
        	// Para controlar el teclado numérico
            valueCode = (e.keyCode < 96) ? e.keyCode : e.keyCode - 48;  
            valueInput = String.fromCharCode(valueCode)
            
            valueText = $(this).val();
            
     		valueFinal = "" + valueText + valueInput;
     		if (valueFinal > 60) e.preventDefault();
     		
        }

        
    });

		
	$("#new1_open-close-ticket").change(function(){

		if ($("#new1_open-close-ticket").prop('checked')) {
			$("#new1_minutes-close-ticket").removeProp("disabled");
			$("#new1_minutes-close-ticket").focus();
				
		} else {
			$("#new1_minutes-close-ticket").val(null);
			$("#new1_minutes-close-ticket").prop("disabled", true);
		}
    	
    });

    

	
    $('#new1_update').button({
        icons: {
            primary: "ui-icon-locked"
        }}).click(function(){
	// Muestra el dialogo y crea un evento
		{
			$('#createRecurringEvent').dialog({
				autoOpen: true,
				width: 700,
				modal: true,
				position: 'middle'
			});
			
	        $("#new1_ttt").css('display','none');
	        $("#new1_start-time").val($("#new1_time_start").val());
	        $("#new1_end-time").val($("#new1_time_end").val());
	        
		};

  	});
	
	$("#new1_repeats").change(function () {
			$("#new1_repeat-options").toggle();
			$('#new1_repeat-options').val(1);
			$(".repeat-fieldset").css('display','none');
			$('#new1_end-repeat').prop('disabled', true);
			$('#1_detail').css('display','block');
            $('#new1_end-repeat').prop('disabled', false);
	});
		
	$("#new1_repeat-options").change(function () {
        $(".repeat-fieldset").css('display','none');	
		$('#new1_end-repeat').prop('disabled', true);
        name = $('#new1_repeat-options option:selected').val();
        //alert(name);
    	if(name=='')
    	{
        	//alert(name+"_detail");
    	}
    	else    	{
    		$('#'+name+'_detail').css('display','block');
			$('#new1_end-repeat').prop('disabled', false);
      	}
	});


	$('.needed_tem').change(function(){
		
			var element_count = 0;
			$('.needed_tem').each(function(){
			   
// 			    if($(this).val() =='')
// 			    {

// 			    }
				if ($(this).prop('type')==="checkbox") {
					element_count =($(this).prop( "checked"))?element_count:1;
// 				} else if ($(this).prop('type')==="checkbox") {
// 					element_count =($(this).prop( "checked"))?element_count:1;
				} else {
					element_count =($(this).val() =='')?1:element_count;
console.log($(this).attr('id'), 'valor: '+$(this).val(), $(this).prop('type'));
				}


			});

			if (element_count === 0) {
				ChangeButton('new1_save',1, false);
			    
			} else {
			    ChangeButton('new1_save',0.5, true);
			    
			}
		//console.log($(this));
	});
	
	$("#new1_start-time").timepicker({
		showButtonPanel: true,
		stepMinute: 5,
		timeFormat: 'hh:mm',
		amNames: ['a.m.', 'AM', 'A'],
		pmNames: ['p.m.', 'PM', 'P'],
		ampm: false,
		firstDay: 1,
		dateFormat: 'dd-mm-yy'
	});

	$("#new1_end-repeat").datepicker({
		showButtonPanel: true,
		stepMinute: 5,
		timeFormat: 'hh:mm',
		amNames: ['a.m.', 'AM', 'A'],
		pmNames: ['p.m.', 'PM', 'P'],
		ampm: false,
		firstDay: 1,
		dateFormat: 'dd-mm-yy'
	});
	
	
	$("#new1_end-time").timepicker({
		showButtonPanel: true,
		stepMinute: 5,
		timeFormat: 'hh:mm',
		amNames: ['a.m.', 'AM', 'A'],
		pmNames: ['p.m.', 'PM', 'P'],
		ampm: false,
		firstDay: 1,
		dateFormat: 'dd-mm-yy'
	});
	
	   // $('#new1_create').button({
        // icons: {
            // primary: "ui-icon-locked"
        // }}).click(function () {
        // $("#createRecurringEvent").attr('style','display: block !important');
        // name = $('#new1_repeat-options option:selected').val();
        // if(name =='1')
        // {
            // var chkArray = [];
//             
            // /* look for all checkboes that have a class 'chk' attached to it and check if it was checked */
// 
            // $(".day_chk:checked").each(function() {
                // chkArray.push($(this).val());
            // });
            // selected = chkArray.join(',') + ",";
            // /*myItems = [{"X":0,"Y":0,"W":0,"H":500},
            // {"X":358,"Y":62,"W":200,"H":500}];
 			// $('#new1_value_recur').val(JSON.stringify(myItems));*/
            // $('#new1_value_recur').val(selected);
        // }
        // else
        // {
        	// $('#new1_value_recur').val($("#new1_"+name+"_locate").val() || []);
        // }    
        // $('#new1_value1_recur').val($(".cl_"+name+"_locate").val());
        // $('#new1_key_recur').val($("#new1_"+name+"_locate").attr("data-type").replace('...',"$('#new1_value1_recur').val()"));
//         
        // $("#new1_time_start").val($("#new1_start-time").val());
        // $("#new1_recur").val($('#new1_repeats').prop('checked'));    
        // $("#new1_time_end").val($("#new1_end-time").val());
        // $("#new1_until").val($("#new1_end-repeat").val());
        // //$("#new1_template_form").submit();
 // });

	$("h3").css({"cursor":"pointer"}).click(function () {
	$('.img_sty').fadeTo( "slow" , 1);
	//opacity: 0.4;filter: alpha(opacity=40);
		$(this).next("div").slideToggle("slow");
		$(this).children().fadeTo( "slow" , 0.4);
		stext = $(this).children("")[0].src;
		if(stext.search('details_close') == -1)
		{
			$(this).children("")[0].src = '/img/details_close.png';
		}
		else
		{
			$(this).children("")[0].src = '/img/details_open.png';
		}
 	});
	
	
    $("#new1_allday").change(function () {
    	
        $("#time-label, #time-element").toggle();
        $("#time-label, #time-element").val('');
        //$(".repeat-fieldset").css('display','none');
 	});

 	

    $('#new1_save').button({
        icons: {
            primary: "ui-icon-locked"
        }}).click(function () {
			if($(this).css("opacity") === '1')
			{
				//var queryString = $('#new1_template_form').formSerialize(); 
				//$("#new1_template_form").ajaxSubmit({url: '/task/checklist/edit/mngtemplates', type: 'post'});


        				if ($("#new1_open-close-ticket").prop('checked')) {
    						
							if($.isNumeric($("#new1_minutes-close-ticket").val())){

								if ($("#new1_minutes-close-ticket").val() === 0 ||
										$("#new1_minutes-close-ticket").val() > 120){

									alert("Minutes for closing ticket have to be between 1 and 120.");
									return;
								}
								
							} else {
								alert("Minutes for closing ticket have to be numeric between 1 and 120.");
								return;
							}								
						
        				} 
			
                        name = $('#new1_repeat-options option:selected').val();
                        if(name =='1')
                        {
                            var chkArray = [];
                            $(".day_chk:checked").each(function() {
                                chkArray.push(parseInt($(this).val()));
                            });
                            var obj = {fr_tmp:{P1D:chkArray}};
                            console.log(obj);
                            $('#new1_value_recur').val(JSON.stringify(obj));
                        }
                        else
                        {
                            $('#new1_value_recur').val($("#new1_"+name+"_locate").val() || []);
                        }    
                                              //  $('#new1_key_recur').val($("#new1_"+name+"_locate").attr("data-type").replace('...',$('#new1_value1_recur').val()));
                      //  $("#new1_begin").val($("#new1_"+name+"_locate").attr("data-begin").replace('...',bg));
                      //  $("#new1_recur").val($('#new1_repeats').prop('checked'));    
                      //  $("#new1_until").val($("#new1_end-repeat").val());

				        $.post( "/task/calendar/edit/mngtemplates", $( "#new1_template_form" ).serialize()).done(function( data1 ) {
                            $('#createNewTemplate').dialog("close");
                            $('#tablaTemplates').DataTable().ajax.reload();
    					});

					
				} 
		});
	
	$("#new1_time_start").timepicker({
		showButtonPanel: true,
		stepMinute: 5,
		timeFormat: 'hh:mm',
		amNames: ['a.m.', 'AM', 'A'],
		pmNames: ['p.m.', 'PM', 'P'],
		ampm: false,
		firstDay: 1,
		dateFormat: 'dd-mm-yy'
	});
	
	$("#new1_time_end").timepicker({
		showButtonPanel: true,
		stepMinute: 5,
		timeFormat: 'hh:mm',
		amNames: ['a.m.', 'AM', 'A'],
		pmNames: ['p.m.', 'PM', 'P'],
		ampm: false,
		firstDay: 1,
		dateFormat: 'dd-mm-yy'
	});


    $(".textareas").focusin(function () {
    	           $(this).animate({           
    	            height: '150px'
    	            },
    	           "slow"
	   	        )
    	    });

    $(".textareas").focusout(function () {
        $(this).animate({           
         height: '20px'
         },
        "slow"
        )
 });
	
});			

</script>