
<div class="mantenimiento">
	<h1><?=$this->translate('Aplicación cerrada por mantenimiento')?></h1>
	<h2>18:00 hs - 21:00 hs</h2>
	
	<p><?=$this->translate('Durante este período las siguientes aplicaciones dejarán de dar servicio:')?></p>

	<ul>
		<li><span class="azul">Easy.</span><span class="blanco">AUTOMATION</span></li>
		<li><span class="azul">Easy.A</span> <span class="blanco">PROJECTS</span></li>
		<li><span class="azul">Easy.A</span> <span class="blanco">DASHBOARD</span></li>
	</ul>
	
</div>
 
