<div id="pestañas" class="colRightPestañas">
	<div class="menuPestanas">
		
		<ul>
			<li><a href="/admin/ajax_delegaciones" title=""><?=$this->translate->_('Delegaciones')?></a></li>
			<li><a href="/admin/ajax_aplicaciones" title=""><?=$this->translate->_('Gestionar Aplicaciones')?></a></li>
		</ul>
		
	</div>
	
	<div class="contenido">
		<div id="ui-tabs-1"></div>
		
	</div>
</div>



<script type="text/javascript">
$(function() {
	$( "#pestañas" ).tabs({
		cache: false,
		ajaxOptions: {
			type: "post",
			error: function( xhr, status, index, anchor ) {
				$( anchor.hash ).html(errorajax);
			}
		}
	}).children().children().removeClass('ui-widget-header');
	
});

</script>