<div class="colRight">
	<div class="contenido">
		<div class="titulo"><?=$this->translate->_('Deploy Application')?></div>
		
		<p><?=$this->translate->_('ATENCION! si no sabe la utilidad de este apartado no deberia estar aqui. Por favor abandone esta seccion sin realizar ningun cambio.')?></p>
		
		<?php echo $this->formulario?>
		
		
	</div>
</div>



<script type="text/javascript">
$(function() {
	
	
});

</script>