<div id="pestañas" class="colRightPestañas">
	<div class="menuPestanas">
		
		<ul>
			<?php if ($this->menuActivo()->checkRole($this->user,'admin','ajaxpermisos')) {?>
			<li><a href="<?=$this->baseUrl('/admin/ajax_home')?>" title=""><?=$this->translate->_('General')?></a></li>
			<?php }?>
			<?php if ($this->menuActivo()->checkRole($this->user,'admin','ajaxroles')) {?>
			<li><a href="/admin/ajax_modulos" title=""><?=$this->translate->_('Módulos')?></a></li>
			<?php }?>
		</ul>
		
	</div>
	
	<div class="contenido">
		<div id="ui-tabs-1"></div>
		
	</div>
</div>



<script type="text/javascript">
$(function() {
	$( ".boton" ).button();
	
	$( "#pestañas" ).tabs({
		cache: false,
		ajaxOptions: {
			type: "post",
			error: function( xhr, status, index, anchor ) {
				$( anchor.hash ).html(errorajax);
			}
		}
	}).children().children().removeClass('ui-widget-header');
});


</script>