<div class="colRight">
	<div class="contenido">
		<div class="titulo"><?=$this->translate->_('Bienvenido al panel de administracion')?></div>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu orci arcu. Suspendisse potenti. Mauris aliquet tellus eu metus gravida ut porta lacus ullamcorper. Maecenas ac nisi vitae nulla interdum molestie ut ut justo. Morbi pulvinar feugiat tempor. Curabitur arcu sem, porta at fermentum vitae, tristique in neque. Vivamus turpis nisl, lacinia sed ultrices at, pretium a sem. Cras dictum, mauris nec gravida lacinia, tellus massa cursus nisi, a ullamcorper metus sapien et ligula. </p>
		
	</div>
</div>



<script type="text/javascript">
$(function() {
	
});

</script>