<div class="titulo"><?=$this->translate->_('Roles')?></div>

<p><?=$this->translate->_('En esta pestaña encontramos una tabla con la lista de roles de la aplicación. Se pueden desactivar roles y evitar el acceso de los usuarios con el control de estado.')?></p>

<table id="tablaRoles">
	<thead>
		<tr>
			<th  class="id">#</th>
			<th><?=$this->translate->_('Nombre')?></th>
			<th><?=$this->translate->_('Hereda')?></th>
			<th class="estado"><?=$this->translate->_('Estado')?>  <span onmouseover="MyTip('InfoEstado', InfoEstadoDescRol)" onmouseout="UnTip()">?</span></th>
		</tr>
	</thead>
	
	<tbody>
	<?php /*
	if(count($this->list)>0)
	{
		foreach($this->list as $row)
		{
			echo '<tr>';
			echo '<td>'.$row['ID'].'</td>';
			echo '<td>'.$row['name'].'</td>';
			echo '<td>'.$row['hereda'].'</td>';
			echo '<td class="switchButtom"><input name="app_roles#'.$row['ID'].'" type="checkbox" '.(($row['estado']=="on")?"checked":"").' /><span class="hidden">'.$row['estado'].'</span></td>';
			echo '</tr>';
		}
	}*/
	?>
	</tbody>
</table>

<script type="text/javascript">
$(function() {

	/* Definir siempre antes que el datatables 
	$('.switchButtom :checkbox').iphoneStyle({
		duration: 100,
		onChange : changeHandler
		//checkedLabel: 'Si',
		//uncheckedLabel: 'No' 
	});
*/
	$('#tablaRoles').dataTable( {
		"bJQueryUI": false,
		"bStateSave": false,
		"aaSorting": [[ 0, "asc" ]],
		"sPaginationType": "full_numbers",
		"oLanguage": idiomaDataTables,
		"bServerSide": true,
        "sAjaxSource": "/index/serverside/tabla/app_roles",
        "fnDrawCallback": function( oSettings ) {
        	$('.switchButtom :checkbox').iphoneStyle({
        		duration: 100,
        		onChange : function(e){
            		changeHandler(e);
        		}
        	});
          },
       	"fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
			// Añadimos la clase necesaria para el iphoneStyle
			$('td:eq(3)', nRow).attr('class','switchButtom');
		},
		"fnInitComplete": function () {
			$('.dataTables_filter input').attr("placeholder", "Buscar");
		},
		aoColumnDefs: [{ 
			"bSortable": false, 
			"aTargets": ['noSort'] 
		}]
	});
	
	
});

function dialogo(titulo)
{
	var dialogo = $( "<div></div>" ).html(preloader).dialog({
		autoOpen: true,
		position: 'middle',
		modal: true,
		title: titulo,
		width: 1000,
		buttons: {
			"<?php echo $this->translate->_("Cancelar")?>": function() {
				$( this ).dialog( "close" );
			}
			
		}
	}).load('/admin/ajax_roles',function(){dialogo.dialog({position: 'middle'});});
}

</script>

